### ISSUE TITLE
Search string - Regex

### ISSUE THREAD

**Issue by Decode84** [Murmeldyret/P3-Project#55]
Being able to search throug the database and using prefixs like && || and whatever there might be,

**Comment by SilverBrother** [comment]
Database is moved to memory when the program is running. Aside from filtering we haven't split up the reference string ATM, meaning a search with prefix' is impossible. This means that our check through the database will fail unless we handle the strings from Excel first ;(

**Comment by SilverBrother** [comment]
Underassignment is to split the string from Excel into smaller pieces.
