### ISSUE TITLE
Implement Scopus API

### ISSUE THREAD

**Issue by Murmeldyret** [Murmeldyret/P3-Project#57]
The program should be able to request Scopus for references. This is done through the HTTPClient. 
The implementation should include a delegate for parsing the response into a reference.

**Comment by SilverBrother** [comment]
For interactive usage of SCOPUS API (if need be): https://dev.elsevier.com/scopus.html
For specs and descriptions of the different APIs: https://dev.elsevier.com/sc_api_spec.html
