### ISSUE TITLE
Setup spreadsheet model to database

### ISSUE THREAD

**Issue by Decode84** [Murmeldyret/P3-Project#58]
Spreadsheet might need access to some form of database related content.

**Comment by SilverBrother** [comment]
Method for comparing reference in spreadsheet with potential identical reference in database, if it doesn't already exist.

**Comment by SilverBrother** [comment]
Anders made a method for comparing two references with each other.

**Comment by Uewotm90** [comment]
Reference has method for evaluating value equality against another reference instance

**Comment by SilverBrother** [comment]
Method now copies database into program memory, allowing the program access to database related content.
